/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pillow3_low_details_0: THREE.Mesh
    matress_details_0: THREE.Mesh
    Cube026_details_0: THREE.Mesh
    Cube027_details_0: THREE.Mesh
    Cube028_details_0: THREE.Mesh
    Cube029_details_0: THREE.Mesh
    Cube030_details_0: THREE.Mesh
    Cube031_details_0: THREE.Mesh
    Cube032_details_0: THREE.Mesh
    Cube033_details_0: THREE.Mesh
    Cube_details_0: THREE.Mesh
    blanket_low_details_0: THREE.Mesh
    Pot_kitchen_0: THREE.Mesh
    Cylinder006_living_room_0: THREE.Mesh
    sofa011_living_room_0: THREE.Mesh
    sofa002_living_room_0: THREE.Mesh
    Cube008_living_room_0: THREE.Mesh
    Cylinder001_living_room_0: THREE.Mesh
    sofa005_living_room_0: THREE.Mesh
    trashcan_kitchen_0: THREE.Mesh
    sofa010_details_0: THREE.Mesh
    sofa010_details_0001: THREE.Mesh
    tv001_details_0: THREE.Mesh
    Cube001_living_room_0: THREE.Mesh
    Cube035_living_room_0: THREE.Mesh
    Cube036_living_room_0: THREE.Mesh
    sofa003_living_room_0: THREE.Mesh
    Cube014_living_room_0: THREE.Mesh
  }
  materials: {
    details: THREE.MeshStandardMaterial
    kitchen: THREE.MeshStandardMaterial
    living_room: THREE.MeshStandardMaterial
  }
}

export default function ApartmentFurnishings({ ...props }: JSX.IntrinsicElements['group']) {
  const spaceURL = `${process.env.REACT_APP_ASSETS_URL}/apartment-furnishings-transformed.glb`;

  const group = useRef<THREE.Group>(null!)
  const { nodes, materials } = useGLTF(spaceURL, 'https://www.gstatic.com/draco/versioned/decoders/1.4.1/') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="pillow3_low" position={[-4.11, -0.88, 1.69]} rotation={[-2.01, 0, 3.14]} scale={0.61}>
          <mesh name="pillow3_low_details_0" castShadow receiveShadow geometry={nodes.pillow3_low_details_0.geometry} material={materials.details} />
        </group>
        <group name="matress" position={[-4.14, -1.37, 0.8]} rotation={[-Math.PI / 2, 0, 3.14]} scale={0.83}>
          <mesh name="matress_details_0" castShadow receiveShadow geometry={nodes.matress_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube026" position={[5.78, -1.42, -1.44]} rotation={[-Math.PI / 2, 0, 1.56]} scale={0.68}>
          <mesh name="Cube026_details_0" castShadow receiveShadow geometry={nodes.Cube026_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube027" position={[6.06, -1.3, -1.44]} rotation={[-Math.PI / 2, 0, 1.56]} scale={0.76}>
          <mesh name="Cube027_details_0" castShadow receiveShadow geometry={nodes.Cube027_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube028" position={[6.06, -1.42, -1.44]} rotation={[-Math.PI / 2, 0, 1.56]} scale={0.68}>
          <mesh name="Cube028_details_0" castShadow receiveShadow geometry={nodes.Cube028_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube029" position={[5.99, -0.17, -1.43]} rotation={[-1.81, -0.14, 2.1]} scale={0.68}>
          <mesh name="Cube029_details_0" castShadow receiveShadow geometry={nodes.Cube029_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube030" position={[6.26, -0.78, -1.26]} rotation={[-Math.PI / 2, 0, -1.58]} scale={0.68}>
          <mesh name="Cube030_details_0" castShadow receiveShadow geometry={nodes.Cube030_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube031" position={[6.26, -0.78, -1.42]} rotation={[-Math.PI / 2, 0, -1.58]} scale={0.58}>
          <mesh name="Cube031_details_0" castShadow receiveShadow geometry={nodes.Cube031_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube032" position={[6.27, -0.8, -1.42]} rotation={[-Math.PI / 2, 0, -1.58]} scale={0.68}>
          <mesh name="Cube032_details_0" castShadow receiveShadow geometry={nodes.Cube032_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube033" position={[6.25, -0.82, -1.42]} rotation={[-Math.PI / 2, 0, 1.56]} scale={0.68}>
          <mesh name="Cube033_details_0" castShadow receiveShadow geometry={nodes.Cube033_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube" position={[5.89, -0.83, -1.43]} rotation={[-Math.PI / 2, 0, 1.56]} scale={0.68}>
          <mesh name="Cube_details_0" castShadow receiveShadow geometry={nodes.Cube_details_0.geometry} material={materials.details} />
        </group>
        <group name="blanket_low" position={[-4.14, -1.21, 0.83]} rotation={[-Math.PI / 2, 0, 3.14]} scale={0.83}>
          <mesh name="blanket_low_details_0" castShadow receiveShadow geometry={nodes.blanket_low_details_0.geometry} material={materials.details} />
        </group>
        <group name="Cube023" position={[4.37, -1.64, 1.01]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.76} />
        <group name="Pot" position={[-3.69, 1.27, -3.4]} rotation={[-Math.PI / 2, 0, 0.54]}>
          <mesh name="Pot_kitchen_0" castShadow receiveShadow geometry={nodes.Pot_kitchen_0.geometry} material={materials.kitchen} position={[4.86, -5.36, -2.74]} />
        </group>
        <group name="Cylinder006" position={[-0.34, 0.61, 5.1]} rotation={[-Math.PI / 2, 0, 1.01]} scale={1.11}>
          <mesh name="Cylinder006_living_room_0" castShadow receiveShadow geometry={nodes.Cylinder006_living_room_0.geometry} material={materials.living_room} position={[5.79, -0.98, -1.48]} rotation={[0, 0, -Math.PI / 2]} scale={0.76} />
        </group>
        <group name="sofa011" position={[-2.19, 0.69, 4.84]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.9}>
          <mesh name="sofa011_living_room_0" castShadow receiveShadow geometry={nodes.sofa011_living_room_0.geometry} material={materials.living_room} position={[-3.44, 7.31, -2.03]} rotation={[0, 0, Math.PI / 2]} scale={0.69} />
        </group>
        <group name="sofa002" position={[-2.14, 0.7, 3.53]} rotation={[-Math.PI / 2, 0, -2.41]} scale={0.9}>
          <mesh name="sofa002_living_room_0" castShadow receiveShadow geometry={nodes.sofa002_living_room_0.geometry} material={materials.living_room} position={[-6.02, 2.65, -2.03]} rotation={[0, 0, Math.PI / 2]} scale={0.69} />
        </group>
        <group name="Cube008" position={[4.42, -1.5, 0.46]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.72}>
          <mesh name="Cube008_living_room_0" castShadow receiveShadow geometry={nodes.Cube008_living_room_0.geometry} material={materials.living_room} />
        </group>
        <group name="Cylinder001" position={[3.84, -1.04, 0.61]} rotation={[-Math.PI / 2, 0, 1.96]} scale={0.85}>
          <mesh name="Cylinder001_living_room_0" castShadow receiveShadow geometry={nodes.Cylinder001_living_room_0.geometry} material={materials.living_room} />
        </group>
        <group name="sofa005" position={[4.72, -1.37, 0.39]} rotation={[Math.PI / 2, 0, 2.8]} scale={-3.84}>
          <mesh name="sofa005_living_room_0" castShadow receiveShadow geometry={nodes.sofa005_living_room_0.geometry} material={materials.living_room} />
        </group>
        <mesh name="trashcan_kitchen_0" castShadow receiveShadow geometry={nodes.trashcan_kitchen_0.geometry} material={materials.kitchen} position={[-1.34, -1.11, 1.63]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.77} />
        <mesh name="sofa010_details_0" castShadow receiveShadow geometry={nodes.sofa010_details_0.geometry} material={materials.details} position={[-3.85, 0.21, 0.48]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={2.5} />
        <mesh name="sofa010_details_0001" castShadow receiveShadow geometry={nodes.sofa010_details_0001.geometry} material={materials.details} position={[-4.38, -0.12, 0.48]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={2.5} />
        <mesh name="tv001_details_0" castShadow receiveShadow geometry={nodes.tv001_details_0.geometry} material={materials.details} position={[4.7, -0.18, -1.59]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.77} />
        <mesh name="Cube001_living_room_0" castShadow receiveShadow geometry={nodes.Cube001_living_room_0.geometry} material={materials.living_room} position={[5.89, -1.61, 0.6]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.69} />
        <mesh name="Cube035_living_room_0" castShadow receiveShadow geometry={nodes.Cube035_living_room_0.geometry} material={materials.living_room} position={[5.84, -1.18, 1.91]} rotation={[-1.2, -0.07, 1.62]} scale={[0.68, 0.68, 0.6]} />
        <mesh name="Cube036_living_room_0" castShadow receiveShadow geometry={nodes.Cube036_living_room_0.geometry} material={materials.living_room} position={[5.98, -1.18, 0.75]} rotation={[-1.52, 0.33, -3.13]} scale={[0.68, 0.68, 0.6]} />
        <mesh name="sofa003_living_room_0" castShadow receiveShadow geometry={nodes.sofa003_living_room_0.geometry} material={materials.living_room} position={[5.76, -1.13, 1.72]} rotation={[-Math.PI / 2, 0, 0.73]} scale={0.62} />
        <mesh name="Cube014_living_room_0" castShadow receiveShadow geometry={nodes.Cube014_living_room_0.geometry} material={materials.living_room} position={[5.89, -1.61, 0.6]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.69} />
      </group>
    </group>
  )
}
