/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder007: THREE.Mesh
  }
  materials: {}
}

type ActionName = 'Cylinder' | 'Cylinder.002' | 'Cylinder.003' | 'Cylinder.004' | 'Cylinder.005' | 'Cylinder.007'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function ManhattanApartmentWaterWorks({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null!)
  const spaceURL = `${process.env.REACT_APP_ASSETS_URL}/manhattan-apartment-waterworks.glb`;
  // @ts-ignore
  const { nodes, materials, animations } = useGLTF(spaceURL, 'https://www.gstatic.com/draco/versioned/decoders/1.4.1/') as GLTFResult
  // @ts-ignore
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-1.99, -0.87, -1.21]} rotation={[0, 0, -Math.PI / 2]} scale={[0.1, 4.67, 0.1]} >
          <meshPhongMaterial color="#0000FF"  />
        </mesh>
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[1.24, -1.73, -1.21]} scale={[0.1, 0.92, 0.1]} >
          <meshPhongMaterial color="#0000FF"  />
        </mesh>
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-6.68, -0.87, -1.21]} rotation={[0, 1.56, -1.57]} scale={[0.1, 4.67, 0.1]} >
          <meshPhongMaterial color="#0000FF"  />
        </mesh>
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[2.54, -0.87, -1.7]} rotation={[0, 1.56, -1.57]} scale={[0.1, 0.56, 0.1]} >
          <meshPhongMaterial color="#0000FF"  />
        </mesh>
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[5.01, -0.87, -2.16]} rotation={[0, 0, -Math.PI / 2]} scale={[0.1, 2.46, 0.1]} >
          <meshPhongMaterial color="#0000FF"  />
        </mesh>
        <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[6.79, -0.87, -0.19]} rotation={[0, 1.56, -1.57]} scale={[0.1, 2.02, 0.1]} >
          <meshPhongMaterial color="#0000FF"  />
        </mesh>
      </group>
    </group>
  )
}
