/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useEffect, useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import ApartmentFurnishings from "./ApartmentFurnishings";
import ApartmentClicks from "./AppartmentClicks";
import useSceneInteractions from "../hooks/useSceneInteractions";
import ManhattanApartmentColliders from "./ManhattanApartmentColliders";

type GLTFResult = GLTF & {
  nodes: {
    Object_0: THREE.Mesh
    Object_0_1: THREE.Mesh
    Object_0_2: THREE.Mesh
    Object_0_3: THREE.Mesh
  }
  materials: {
    cropped_textured_mesh_0: THREE.MeshBasicMaterial
    cropped_textured_mesh_1: THREE.MeshBasicMaterial
    cropped_textured_mesh_2: THREE.MeshBasicMaterial
    cropped_textured_mesh_3: THREE.MeshBasicMaterial
  }
}

export default function ManhattanApartment({firstPerson, setRoomCount, furnished, selectedMesh, setTarget, setSelectedMesh, setRoomNameArray}: any) {
  // const { furnished, selectedMesh, setTarget } = useSceneInteractions(); // todo figure out why this hook isn't defined

  const spaceURL = `${process.env.REACT_APP_ASSETS_URL}/manhattan-apartment-transformed.glb`;
  const group = useRef<THREE.Group>(null!)
  const ref = useRef<any>(null!)
  // @ts-ignore
  const { nodes, materials } = useGLTF(spaceURL, 'https://www.gstatic.com/draco/versioned/decoders/1.4.1/') as GLTFResult

  useEffect(() => {
    setRoomCount(3);
    setRoomNameArray(['Kitchen', 'Living Room', 'Bedroom']);
  }, [])

  useEffect(() => {
    switch(selectedMesh) {
      case 0:
        setTarget([0,0,0]) // lounge
        break;
      case 1:
        setTarget([5,0,0])
        break;
      case 2:
        setTarget([-4,0,0]) // bedroom
        break;
    }

  }, [selectedMesh])

  return (
    <group ref={group} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.03]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_0.geometry} material={materials.cropped_textured_mesh_0} />
        <mesh castShadow receiveShadow geometry={nodes.Object_0_1.geometry} material={materials.cropped_textured_mesh_1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_0_2.geometry} material={materials.cropped_textured_mesh_2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_0_3.geometry} material={materials.cropped_textured_mesh_3} />
      </group>

      { furnished && (
        <ApartmentFurnishings />
      )}

      { firstPerson && (
        <ManhattanApartmentColliders furnished={furnished} />
      )}

      {/*<ApartmentClicks setSelectedMesh={setSelectedMesh}/>*/}
    </group>
  )
}
